# Generated by Django 4.2.1 on 2023-05-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_Id', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('mode_of_payments', models.CharField(max_length=25)),
                ('amount_spent', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
