# Generated by Django 4.2 on 2023-05-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_emiinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmiInfo',
            new_name='EMIData',
        ),
    ]
